### ISSUE TITLE
Can this toolboox be used to modify reaction bounds?

### ISSUE THREAD

**Issue by akaviaLab** [mcisb/mcisb-recon#2]
Hi.

I'm very impressed by RECON 2.2 and by this toolbox, which looks really useful in both changing a model and keeping a record.
I'm wondering if the toolbox can be used to modify reaction flux (lower and upper) bounds? For example, I have a couple of reactions I would like to change to 0,500. How would I go about that?

Thanks,

Uri David

**Comment by neilswainston** [comment]
Hi Uri David,

Yes, you could write a small module that reads in a file that has a similar format to...

r_reactionid1   0   500
r_reactionid2   0   250

...and then use this to reset flux bounds appropriately.

It would probably be better to do this as one of the last steps in the pipeline, just to ensure that the changes that you make to flux bounds are not overridden elsewhere.

Note that most of the code that updates the model is held in the separate project, https://github.com/mcisb/SuBliMinaLToolbox, which is ambivalent to the host organism and therefore not Recon 2 / human specific.

Cheers,

Neil.
